language: php
php:
- 5.6

before_install:
- wget http://getcomposer.org/composer.phar
- composer install --dev
- composer require phpunit/phpunit:4.8.* satooshi/php-coveralls:dev-master
 
script:
- ./vendor/bin/phpunit --verbose --coverage-clover ./tests/logs/clover.xml
 
after_script:
- php vendor/bin/coveralls -v
