language: python
python:
  - "2.7"
install:
  - pip install selenium
  - pip install pyvirtualdisplay
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
  - pwd
  - cd TestSuite
  - python test-suite-maps.py
  - python test-suite-timeline.py
